name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: build and publish
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Build with Maven
        run: cd microservice && mvn -B package --file pom.xml
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: microservice/Dockerfile
          context: microservice
          tags: user/app:latest
